In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import random
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
df=pd.read_csv("energy.txt",sep="\s+")
data=df.iloc[:,0:8]
y=df.iloc[:,-1:]
for col in data:
    data.loc[data.sample(frac=0.1,random_state=None).index, col] = np.nan

In [3]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X2=imp.fit(data)
X2=imp.transform(data)
X2=MinMaxScaler().fit_transform(X2)
data01=df.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
MAE=np.abs(data01-X2)
aa=MAE.mean()
print(aa)
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae11 = mean_absolute_error(y_test, y_pred)
print(mae11)
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data)
train1=MinMaxScaler().fit_transform(train)
data01=df.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
MAE=np.abs(data01-train1)
bb=MAE.mean()
print(bb)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae12 = mean_absolute_error(y_test, y_pred)
print(mae12)
mice_imputer = IterativeImputer()
data01=df.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
X4= mice_imputer.fit_transform(data)
X5=MinMaxScaler().fit_transform(X4)
MAE=np.abs(data01-X5)
cc=MAE.mean()
print(cc)
X_train, X_test, y_train, y_test = train_test_split(X5, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae13 = mean_absolute_error(y_test, y_pred)
print(mae13)
Z=data.copy(deep=True)
Z[Z>=0]=0
Z[Z<0]=0
Z=Z.fillna(value=1)
data2=pd.concat([data,Z],axis=1)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
Z2=imp.fit(data2)
Z2=imp.transform(data2)
Z2=MinMaxScaler().fit_transform(Z2)
data01=df.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
data02=np.append(data01,data01,axis=1)
MAE=np.abs(data02-Z2)
dd=MAE.mean()
print(dd)
X_train, X_test, y_train, y_test = train_test_split(Z2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae14 = mean_absolute_error(y_test, y_pred)
print(mae14)
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data2)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data02-train1)
ee=MAE.mean()
print(ee)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae15 = mean_absolute_error(y_test, y_pred)
print(mae15)
mice_imputer = IterativeImputer()
Z1= mice_imputer.fit_transform(data2)
Z3=MinMaxScaler().fit_transform(Z1)
MAE=np.abs(data02-Z3)
ff=MAE.mean()
print(ff)
X_train, X_test, y_train, y_test = train_test_split(Z3, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae16 = mean_absolute_error(y_test, y_pred)
print(mae16)

0.03196623780738176
2.963508285505554
0.016642123429232804
2.37653374099159
0.05313664756685322
2.4068002628696483
0.2729059265467133
3.043224161698032
0.2646621784835896
2.441257633983395
0.2713800087312525
2.3195042736921314


In [4]:
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
imputer = MissForest()
X_imputed = imputer.fit_transform(data)
X_imputed=MinMaxScaler().fit_transform(X_imputed)
MAE=np.abs(data01-X_imputed)
gg=MAE.mean()
print(gg)
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae17 = mean_absolute_error(y_test, y_pred)
print(mae17)

C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 0


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 1


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 2


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 3


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 4
0.015191406056237785
2.3797772507440476


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


In [5]:
import miceforest as mf
import pandas as pd
kernel = mf.ImputationKernel(
  data=data,
  save_all_iterations=True,
  random_state=1991
)
new_data = data.iloc[range(768)]
new_data_imputed = kernel.impute_new_data(new_data)
new_completed_data = new_data_imputed.complete_data(0)
new_completed_data =MinMaxScaler().fit_transform(new_completed_data)
MAE=np.abs(data01-new_completed_data)
hh=MAE.mean()
print(hh)
X_train, X_test, y_train, y_test = train_test_split(new_completed_data, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae18 = mean_absolute_error(y_test, y_pred)
mae18

0.040727629484953703


3.3715678936982307

In [6]:
from tqdm import tqdm
import torch.nn.functional as F
use_gpu = False  # set it to True to use GPU and False to use CPU

if use_gpu:
    torch.cuda.set_device(0)
data1=df.iloc[:,0:8]
#%% System Parameters
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.1
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0.0

#%% Data

# Data generation
Data = data1
# Parameters
Data = np.array(Data,type(float))
No = len(Data)
Dim = len(Data[0,:])

# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim

# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

#%% Necessary Functions

# 1. Xavier Initialization Definition
# def xavier_init(size):
#     in_dim = size[0]
#     xavier_stddev = 1. / tf.sqrt(in_dim / 2.)
#     return tf.random_normal(shape = size, stddev = xavier_stddev)
def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)

In [7]:
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
M_mb = M_mb.astype(float)
X_mb = testX
X_mb = X_mb.astype(float)

New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
print("Imputed test data:")
np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())
A=imputed_data.detach().numpy()
MAE=np.abs(data01-A)
ii=MAE.mean()
print(ii)
X_train, X_test, y_train, y_test = train_test_split(imputed_data.detach().numpy(), y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae19 = mean_absolute_error(y_test, y_pred)
mae19

Imputed test data:
[[0.58189421 0.83333333 0.42857143 ... 0.66666644 0.62499844 0.19999996]
 [0.24999931 0.66666666 0.14285714 ... 0.99999967 0.99999750 0.59991693]
 [0.00000000 1.00000000 0.71428571 ... 0.00000000 0.62499844 0.59999988]
 ...
 [0.24999931 0.66666666 0.14285714 ... 0.66666644 0.99999750 0.39999992]
 [0.38888781 0.50000000 0.41219505 ... 0.99999967 0.99999750 0.39999992]
 [0.05555540 0.91666666 0.57142857 ... 0.99999967 0.62499844 0.59999988]]
0.36751025497911405


9.363727326409732

In [8]:
df1=pd.read_csv("energy.txt",sep="\s+")
dataa=df1.iloc[:,0:8]
y=df1.iloc[:,-1:]
for col in dataa :
    dataa.loc[dataa.sample(frac=0.3,random_state=None).index, col] = np.nan
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
A2=imp.fit(dataa)
A2=imp.transform(dataa)
A2=MinMaxScaler().fit_transform(A2)
data01=df1.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
MAE=np.abs(data01-A2)
aa2=MAE.mean()
print(aa2)
X_train, X_test, y_train, y_test = train_test_split(A2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae211 = mean_absolute_error(y_test, y_pred)
print(mae211)
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data01-train1)
bb2=MAE.mean()
print(bb2)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae212 = mean_absolute_error(y_test, y_pred)
print(mae212)
mice_imputer = IterativeImputer()
A4= mice_imputer.fit_transform(data)
A5=MinMaxScaler().fit_transform(A4)
data02=np.append(data01,data01,axis=1)
MAE=np.abs(data01-A5)
cc2=MAE.mean()
print(cc2)
X_train, X_test, y_train, y_test = train_test_split(A5, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae213 = mean_absolute_error(y_test, y_pred)
print(mae213)
Z=dataa.copy(deep=True)
Z[Z>=0]=0
Z[Z<0]=0
Z=Z.fillna(value=1)
data2=pd.concat([dataa,Z],axis=1)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
Z2=imp.fit(data2)
Z2=imp.transform(data2)
Z2=MinMaxScaler().fit_transform(Z2)
data02=np.append(data01,data01,axis=1)
MAE=np.abs(data02-Z2)
dd2=MAE.mean()
print(dd2)
X_train, X_test, y_train, y_test = train_test_split(Z2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae214 = mean_absolute_error(y_test, y_pred)
print(mae214)
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data2)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data02-train1)
ee2=MAE.mean()
print(ee2)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae215 = mean_absolute_error(y_test, y_pred)
print(mae215)
mice_imputer = IterativeImputer()
Z1= mice_imputer.fit_transform(data2)
Z3=MinMaxScaler().fit_transform(Z1)
MAE=np.abs(data02-Z3)
ff2=MAE.mean()
print(ff2)
X_train, X_test, y_train, y_test = train_test_split(Z3, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae216 = mean_absolute_error(y_test, y_pred)
print(mae216)
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
imputer = MissForest()
X_imputed = imputer.fit_transform(dataa)
data01=df1.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
X_imputed=MinMaxScaler().fit_transform(X_imputed)
#data02=np.append(data01,data01,axis=1)
MAE=np.abs(data01-X_imputed)
gg2=MAE.mean()
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae217 = mean_absolute_error(y_test, y_pred)
print(gg2,mae217)
import miceforest as mf
import pandas as pd
kernel = mf.ImputationKernel(
  data=data,
  save_all_iterations=True,
  random_state=1991
)
new_data = data.iloc[range(768)]
new_data_imputed = kernel.impute_new_data(new_data)
new_completed_data = new_data_imputed.complete_data(0)
new_completed_data =MinMaxScaler().fit_transform(new_completed_data)
MAE=np.abs(data01-new_completed_data)
hh2=MAE.mean()
print(hh2)
X_train, X_test, y_train, y_test = train_test_split(new_completed_data, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae218 = mean_absolute_error(y_test, y_pred)
mae218

0.09334006742912342
4.2680087357791665
0.016642123429232804
2.37653374099159
0.05313664756685322
2.4068002628696483
0.29771389635510404
4.292706988784117
0.27658353936735286
3.159710899690548
0.314272515981639
3.0591402153237155


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 0


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 1


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 2
0.04010661464126652 2.6150167211839386
0.040727629484953703


3.3715678936982307

In [9]:
from tqdm import tqdm
import torch.nn.functional as F
use_gpu = False  # set it to True to use GPU and False to use CPU

if use_gpu:
    torch.cuda.set_device(0)
data1=df1.iloc[:,0:8]
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.3
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0

#%% Data
# Data generation
Data = data01
# Parameters
Data = np.array(Data,type(float))
No = len(Data)
Dim = len(Data[0,:])
# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim
# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
M_mb = M_mb.astype(float)
X_mb = testX
X_mb = X_mb.astype(float)

New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
        
#print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
#print("Imputed test data:")
np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())
A=imputed_data.detach().numpy()
MAE=np.abs(data01-A)
ii2=MAE.mean()
print(ii2)
X_train, X_test, y_train, y_test = train_test_split(imputed_data.detach().numpy(), y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae219 = mean_absolute_error(y_test, y_pred)
print(mae219)

[[0.57493133 0.83333250 0.42857100 ... 0.66666600 0.99999900 0.39279667]
 [0.76048653 0.24999975 0.28571400 ... 0.00000000 0.99999900 0.99999900]
 [0.55555500 0.53066158 0.42857100 ... 0.66666600 0.51828431 0.48434315]
 ...
 [0.33333300 0.58333275 0.00000000 ... 0.11546499 0.24999975 0.79999920]
 [0.99999900 0.61894364 0.49678328 ... 0.00000000 0.99999900 0.42202400]
 [0.48326485 0.56102973 0.57142800 ... 0.33333300 0.47645620 0.48991613]]
0.37615344787401833
9.318347982463749


In [10]:
df2=pd.read_csv("energy.txt",sep="\s+")
datab=df2.iloc[:,0:8]
y=df2.iloc[:,-1:]
for col in datab :
    datab.loc[datab.sample(frac=0.5,random_state=None).index, col] = np.nan
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
A2=imp.fit(datab)
A2=imp.transform(datab)
A2=MinMaxScaler().fit_transform(A2)
data01=df2.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
MAE=np.abs(data01-A2)
aa3=MAE.mean()
print(aa3)
X_train, X_test, y_train, y_test = train_test_split(A2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae311 = mean_absolute_error(y_test, y_pred)
print(mae311)
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data01-train1)
bb3=MAE.mean()
print(bb3)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae312 = mean_absolute_error(y_test, y_pred)
print(mae312)
mice_imputer = IterativeImputer()
A4= mice_imputer.fit_transform(data)
A5=MinMaxScaler().fit_transform(A4)
MAE=np.abs(data01-A5)
cc3=MAE.mean()
print(cc3)
X_train, X_test, y_train, y_test = train_test_split(A5, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae313 = mean_absolute_error(y_test, y_pred)
print(mae313)
Z=datab.copy(deep=True)
Z[Z>=0]=0
Z[Z<0]=0
Z=Z.fillna(value=1)
data2=pd.concat([datab,Z],axis=1)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
Z2=imp.fit(data2)
Z2=imp.transform(data2)
Z2=MinMaxScaler().fit_transform(Z2)
data02=np.append(data01,data01,axis=1)
MAE=np.abs(data02-Z2)
dd3=MAE.mean()
print(dd3)
X_train, X_test, y_train, y_test = train_test_split(Z2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae314 = mean_absolute_error(y_test, y_pred)
print(mae314)
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data2)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data02-train1)
ee3=MAE.mean()
print(ee3)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae315 = mean_absolute_error(y_test, y_pred)
print(mae315)
mice_imputer = IterativeImputer()
Z1= mice_imputer.fit_transform(data2)
Z3=MinMaxScaler().fit_transform(Z1)
MAE=np.abs(data02-Z3)
ff3=MAE.mean()
print(ff3)
X_train, X_test, y_train, y_test = train_test_split(Z3, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae316 = mean_absolute_error(y_test, y_pred)
print(mae316)
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
imputer = MissForest()
X_imputed = imputer.fit_transform(dataa)
data01=df2.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
X_imputed=MinMaxScaler().fit_transform(X_imputed)
MAE=np.abs(data01-X_imputed)
gg3=MAE.mean()
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae317 = mean_absolute_error(y_test, y_pred)
print(gg3,mae317)
import miceforest as mf
import pandas as pd
kernel = mf.ImputationKernel(
  data=data,
  save_all_iterations=True,
  random_state=1991
)
new_data = data.iloc[range(768)]
new_data_imputed = kernel.impute_new_data(new_data)
new_completed_data = new_data_imputed.complete_data(0)
new_completed_data =MinMaxScaler().fit_transform(new_completed_data)
MAE=np.abs(data01-new_completed_data)
hh3=MAE.mean()
print(hh3)
X_train, X_test, y_train, y_test = train_test_split(new_completed_data, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae318 = mean_absolute_error(y_test, y_pred)
mae318

0.15603365553329443
5.129026579923499
0.016642123429232804
2.37653374099159
0.05313664756685322
2.4068002628696483
0.3294336830287173
5.1721299524556095
0.30447646045180227
3.893745372675366
0.35219235664505044
3.9063070380721228


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 0


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 1


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 2


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 3


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 4
0.04013169136383774 2.63279022384489
0.040727629484953703


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(


3.3715678936982307

In [11]:
from tqdm import tqdm
import torch.nn.functional as F
use_gpu = False  # set it to True to use GPU and False to use CPU

if use_gpu:
    torch.cuda.set_device(0)
data1=df2.iloc[:,0:8]
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.5
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0

#%% Data
# Data generation
Data = data01
# Parameters
Data = np.array(Data,type(float))
No = len(Data)
Dim = len(Data[0,:])
# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim
# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
M_mb = M_mb.astype(float)
X_mb = testX
X_mb = X_mb.astype(float)

New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
        
#print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
#print("Imputed test data:")
np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())
A=imputed_data.detach().numpy()
MAE=np.abs(data01-A)
ii3=MAE.mean()
print(ii3)
X_train, X_test, y_train, y_test = train_test_split(imputed_data.detach().numpy(), y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae319 = mean_absolute_error(y_test, y_pred)
print(mae319)

[[0.19444425 0.74999925 0.28571400 ... 0.37555861 0.00000000 0.46194912]
 [0.38888850 0.49999950 0.53927706 ... 0.41046432 0.99999900 0.49746870]
 [0.53624861 0.91666575 0.57142800 ... 0.99999900 0.62499938 0.43456050]
 ...
 [0.51273033 0.36074299 0.42857100 ... 0.41172866 0.62499938 0.59999940]
 [0.48825631 0.99999900 0.49537319 ... 0.50090574 0.24999975 0.49205912]
 [0.77777700 0.29367394 0.60695540 ... 0.54045823 0.99999900 0.59999940]]
0.35448583999077404
9.336384870576214


In [12]:
df3=pd.read_csv("energy.txt",sep="\s+")
datac=df3.iloc[:,0:8]
y=df3.iloc[:,-1:]
for col in datac :
    datac.loc[datab.sample(frac=0.7,random_state=None).index, col] = np.nan
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
A2=imp.fit(datac)
A2=imp.transform(datac)
A2=MinMaxScaler().fit_transform(A2)
data01=df3.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
MAE=np.abs(data01-A2)
aa4=MAE.mean()
print(aa4)
X_train, X_test, y_train, y_test = train_test_split(A2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae411 = mean_absolute_error(y_test, y_pred)
print(mae411)
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data01-train1)
bb4=MAE.mean()
print(bb4)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae412 = mean_absolute_error(y_test, y_pred)
print(mae412)
mice_imputer = IterativeImputer()
A4= mice_imputer.fit_transform(data)
A5=MinMaxScaler().fit_transform(A4)
MAE=np.abs(data01-A5)
cc4=MAE.mean()
print(cc4)
X_train, X_test, y_train, y_test = train_test_split(A5, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae413 = mean_absolute_error(y_test, y_pred)
print(mae413)
Z=datac.copy(deep=True)
Z[Z>=0]=0
Z[Z<0]=0
Z=Z.fillna(value=1)
data2=pd.concat([datab,Z],axis=1)
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
Z2=imp.fit(data2)
Z2=imp.transform(data2)
Z2=MinMaxScaler().fit_transform(Z2)
data02=np.append(data01,data01,axis=1)
MAE=np.abs(data02-Z2)
dd4=MAE.mean()
print(dd4)
X_train, X_test, y_train, y_test = train_test_split(Z2, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae414 = mean_absolute_error(y_test, y_pred)
print(mae414)
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")
train = knn_imputer.fit_transform(data2)
train1=MinMaxScaler().fit_transform(train)
MAE=np.abs(data02-train1)
ee4=MAE.mean()
print(ee4)
X_train, X_test, y_train, y_test = train_test_split(train1, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae415 = mean_absolute_error(y_test, y_pred)
print(mae415)
mice_imputer = IterativeImputer()
Z1= mice_imputer.fit_transform(data2)
Z3=MinMaxScaler().fit_transform(Z1)
MAE=np.abs(data02-Z3)
ff4=MAE.mean()
print(ff4)
X_train, X_test, y_train, y_test = train_test_split(Z3, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae416 = mean_absolute_error(y_test, y_pred)
print(mae416)
import sys
import sklearn.neighbors._base
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
imputer = MissForest()
X_imputed = imputer.fit_transform(dataa)
data01=df3.iloc[:,0:8]
data01=MinMaxScaler().fit_transform(data01)
X_imputed=MinMaxScaler().fit_transform(X_imputed)
MAE=np.abs(data01-X_imputed)
gg4=MAE.mean()
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae417 = mean_absolute_error(y_test, y_pred)
print(gg4,mae417)
import miceforest as mf
import pandas as pd
kernel = mf.ImputationKernel(
  data=data,
  save_all_iterations=True,
  random_state=1991
)
new_data = data.iloc[range(768)]
new_data_imputed = kernel.impute_new_data(new_data)
new_completed_data = new_data_imputed.complete_data(0)
new_completed_data =MinMaxScaler().fit_transform(new_completed_data)
MAE=np.abs(data01-new_completed_data)
hh4=MAE.mean()
print(hh4)
X_train, X_test, y_train, y_test = train_test_split(new_completed_data, y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae418 = mean_absolute_error(y_test, y_pred)
mae418

0.21823544962312372
6.16031251425128
0.016642123429232804
2.37653374099159
0.05313664756685322
2.4068002628696483
0.3234652843845374
5.105638255351397
0.3154110378689236
4.9081433018973195
0.3464076032406438
4.034884995918132


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 0


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 1


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 2


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 3


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 4


C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:388: FutureWarning: Criter

Iteration: 5
0.039617329780807536 2.6568395911359803
0.040727629484953703


3.3715678936982307

In [13]:
from tqdm import tqdm
import torch.nn.functional as F
use_gpu = False  # set it to True to use GPU and False to use CPU

if use_gpu:
    torch.cuda.set_device(0)
data1=df3.iloc[:,0:8]
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.7
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0

#%% Data
# Data generation
Data = data01
# Parameters
Data = np.array(Data,type(float))
No = len(Data)
Dim = len(Data[0,:])
# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim
# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
M_mb = M_mb.astype(float)
X_mb = testX
X_mb = X_mb.astype(float)

New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
        
#print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
#print("Imputed test data:")
np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())
A=imputed_data.detach().numpy()
MAE=np.abs(data01-A)
ii4=MAE.mean()
print(ii4)
X_train, X_test, y_train, y_test = train_test_split(imputed_data.detach().numpy(), y, test_size=0.3, random_state=0)
reg_all = LinearRegression()
reg_all.fit(X_train,y_train)
y_pred = reg_all.predict(X_test)
score = reg_all.score(X_test, y_test)
mae419 = mean_absolute_error(y_test, y_pred)
print(mae419)

[[0.19444425 0.74999925 0.58731320 ... 0.34028426 0.62499938 0.79999920]
 [0.42859662 0.30738632 0.55302461 ... 0.38901539 0.62499938 0.59413455]
 [0.33333300 0.58333275 0.49835060 ... 0.49992605 0.50949664 0.51854733]
 ...
 [0.05555550 0.41053965 0.44091794 ... 0.33333300 0.24999975 0.55011434]
 [0.49990639 0.49932260 0.50055502 ... 0.49952582 0.49965621 0.50121482]
 [0.49957010 0.49928790 0.50106811 ... 0.49928254 0.49932737 0.50170875]]
0.34181918406957923
9.2129550528093


In [15]:
import matplotlib.pyplot as plt
%pylab
N=[0.1,0.3,0.5,0.7]
M1=[aa,aa2,aa3,aa4]
M2=[bb,bb2,bb3,bb4]
M3=[cc,cc2,cc3,cc4]
M4=[dd,dd2,dd3,dd4]
M5=[ee,ee2,ee3,ee4]
M6=[ff,ff2,ff3,ff4]
M7=[gg,gg2,gg3,gg4]
M8=[hh,hh2,hh3,hh4]
M9=[ii,ii2,ii3,ii4]
plt.xlim([0.1,0.7])
plt.xticks(np.arange(0.1,0.9,0.2))# x軸邊界
plt.xlabel('Missing Data Ratio')
plt.ylabel('Missing Value Imputation Ratio--MAE')
plt.title('energy')
plt.plot(N,M1,label='mean')
plt.plot(N,M2,label='knn')
plt.plot(N,M3,label='mice')
plt.plot(N,M4,label='meanmi')
plt.plot(N,M5,label='knnmi')
plt.plot(N,M6,label='micemi')
plt.plot(N,M7,label='missforest')
plt.plot(N,M8,label='miceforest')
plt.plot(N,M9,label='gain')
plt.legend(loc='best')
figsize(6,5)
plt.show()

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [16]:
import matplotlib.pyplot as plt
%pylab
N=[0.1,0.3,0.5,0.7]
M1=[mae11,mae211,mae311,mae411]
M2=[mae12,mae212,mae312,mae412]
M3=[mae13,mae213,mae313,mae413]
M4=[mae14,mae214,mae314,mae414]
M5=[mae15,mae215,mae315,mae415]
M6=[mae16,mae216,mae316,mae416]
M7=[mae17,mae217,mae317,mae417]
M8=[mae18,mae218,mae318,mae418]
M9=[mae19,mae219,mae319,mae419]
plt.xlim([0,0.8])
plt.xticks(np.arange(0.1,0.9,0.2))# x軸邊界
plt.xlabel('Missing Data Ratio')
plt.ylabel('Target Regression Prediction Test--MAE')
plt.title('energy')
plt.plot(N,M1,label='mean')
plt.plot(N,M2,label='knn')
plt.plot(N,M3,label='mice')
plt.plot(N,M4,label='meanmi')
plt.plot(N,M5,label='knnmi')
plt.plot(N,M6,label='micemi')
plt.plot(N,M7,label='missforest')
plt.plot(N,M8,label='miceforest')
plt.plot(N,M9,label='gain')
plt.legend(loc='best')
figsize(5,5)
plt.show()

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib
